### ISSUE TITLE
Your Resume is not visible in README.md

### ISSUE THREAD

**Issue by divyanshu-rawat** [vicky002/TheUltimateInternshipGuide#6]
Reason is (https://raw.githubusercontent.com/vicky002/vicky002.github.io/master/img/Resume.png) is no longer valid.

**Comment by divyanshu-rawat** [comment]
Reason is (https://raw.githubusercontent.com/vicky002/vicky002.github.io/master/img/Resume.png) is no longer valid.

**Comment by vicky002** [comment]
Above link is working fine.
